apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api
  namespace: payment-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::757906495185:role/payment-api-eks-payment-api-role